const mongoose = require('../config/miniMongoose');

// A predictive street-sweeping recommendation for a zone/road. Generated by the
// Sweeping Engine from footfall, commercial density, markets, weather, events
// and historical dirt accumulation. Backs the "where / how often to sweep" UI.
const sweepingNeedSchema = new mongoose.Schema(
  {
    zone: { type: mongoose.Schema.Types.ObjectId, ref: 'Zone', default: null },
    landmark: { type: mongoose.Schema.Types.ObjectId, ref: 'Landmark', default: null },
    location: {
      lat: { type: Number, default: null },
      lng: { type: Number, default: null },
    },
    roadType: {
      type: String,
      enum: ['main', 'market', 'residential', 'food_street', 'park', 'highway'],
      default: 'residential',
    },
    // Road Dirt Accumulation Score (0-100) — how urgently this area needs sweeping
    dirtScore: { type: Number, min: 0, max: 100, default: 0 },
    // Recommended sweeping frequency (visits per week)
    frequencyPerWeek: { type: Number, default: 1 },
    // When recommended (calendar-ish label, e.g. 'daily', '3x/week', '1x/week')
    frequencyLabel: { type: String, default: '1x/week' },
    peakStartHour: { type: Number, default: null },
    peakEndHour: { type: Number, default: null },
    priority: { type: Number, min: 0, max: 100, default: 0 },
    contributors: { type: [String], default: [] },
    eventMultiplier: { type: Number, default: 1 },
  },
  { timestamps: true }
);

sweepingNeedSchema.index({ zone: 1, priority: -1 });

module.exports = mongoose.model('SweepingNeed', sweepingNeedSchema);
