/**
 * NagarAI Event Intelligence Engine
 *
 * Detects an event and estimates its sanitation impact:
 *   - waste spike multiplier (from base event type + attendance)
 *   - extra bins / vehicles / sweepers required
 *   - recommended collection frequency and peak window
 *   - waste-type composition changes (organic/plastic lifts)
 *
 * The base multiplier table can later be re-learned from historical events.
 */

// Base waste multiplier by event type (also in timeFeatures — keep in sync).
const EVENT_BASE_MULTIPLIER = {
  festival: 2.5,
  concert: 3.0,
  sports: 2.2,
  fair: 2.0,
  wedding: 1.8,
  religious: 1.6,
  political: 2.0,
  university: 1.8,
  market: 1.5,
  holiday: 1.2,
  other: 1.3,
};

// kg per attendee per day contributed to waste (rough urban estimate)
const KG_PER_ATTENDEE = 0.08;

// Capacity per temporary bin (L). Assume ~0.9 usable → kg.
const tmpBinCapacityL = 660;
const usabilityFactor = 0.9;
const kgPerTmpBin = tmpBinCapacityL * usabilityFactor; // ~594 kg if we equate L≈kg for demo scale

// Extra vehicles absorb (kg) each trip
const vehicleAbsorbKg = 4000;
// One sweeper-hours per N kg of organic/food waste
const sweeperPerKg = 0.002;

/**
 * Compute the sanitation impact for an event.
 * @param {object} params { type, expectedAttendance, name }
 */
const computeEventImpact = ({ type = 'other', expectedAttendance = 0, name = '' } = {}) => {
  const att = Math.max(0, expectedAttendance);
  const baseMult = EVENT_BASE_MULTIPLIER[type] || EVENT_BASE_MULTIPLIER.other;

  // Attendance gently escalates the multiplier but is bounded (diminishing returns)
  // Calibrated so a large festival (~25k) lands near the PRD's 2.8× spike.
  const attendanceFactor = 1 + Math.min(0.3, att / 100000);
  const wasteMultiplier = Math.round(baseMult * attendanceFactor * 100) / 100;

  // Extra estimated kg/day generated by the event
  const extraKgDay = att * KG_PER_ATTENDEE * wasteMultiplier;

  // Temporary bins needed to absorb the extra load
  const extraBins = Math.max(0, Math.round((extraKgDay / kgPerTmpBin) / 2)); // collected ~2x/day

  // Extra vehicles (each does ~2 trips/day absorbing vehicleAbsorbKg)
  const extraVehicles = Math.max(0, Math.round(extraKgDay / (vehicleAbsorbKg * 2)));

  // Extra sweepers (sweeper-hours ≈ sweeperPerKg * extraKg, over ~4h shifts)
  const sweeperHours = sweeperPerKg * extraKgDay;
  const extraSweepers = Math.max(0, Math.round(sweeperHours / 4));

  // Collection frequency: higher spike → shorter interval
  const collectionFrequencyHrs = wasteMultiplier >= 3 ? 2 : wasteMultiplier >= 2 ? 3 : 4;

  // Peak window: evening (18-23) with spill into late night for big events
  const peakWasteStart = 18;
  const peakWasteEnd = att >= 15000 ? 24 : 22;

  // Waste composition shift; food/organic and plastic both rise
  const organicMultiplier = Math.round(baseMult * 1.2 * 10) / 10;
  const plasticMultiplier = Math.round(baseMult * 0.95 * 10) / 10;

  return {
    name,
    type,
    expectedAttendance: att,
    wasteMultiplier,
    extraKgDay: Math.round(extraKgDay),
    extraBins,
    extraVehicles,
    extraSweepers,
    collectionFrequencyHrs,
    peakWasteStart,
    peakWasteEnd,
    organicMultiplier,
    plasticMultiplier,
  };
};

module.exports = { computeEventImpact, EVENT_BASE_MULTIPLIER };
